### 请求 /infra/file-config/create 接口 => 成功
POST {{baseUrl}}/infra/file-config/create
Content-Type: application/json
tenant-id: {{adminTenentId}}
Authorization: Bearer {{token}}

{
  "name": "S3 - test",
  "remark": "",
  "storage": 0,
  "config": {
    "accessKey": "DUADLSAJ7P7PADES9FWJ",
    "accessSecret": "RdJKBDkJZslrgON3WgsIDzaKpBJvDRd37xwRAOd0",
    "bucket": "ruoyi-vue-pro",
    "endpoint": "10.165.8.176:8080",
    "domain": "http://10.165.8.176:8080",
    "region": ""
  }
}

### 请求 /infra/file-config/update 接口 => 成功
PUT {{baseUrl}}/infra/file-config/update
Content-Type: application/json
tenant-id: {{adminTenentId}}
Authorization: Bearer {{token}}

{
  "id": 2,
  "name": "S3 - test",
  "remark": "",
  "config": {
    "accessKey": "DUADLSAJ7P7PADES9FWJ",
    "accessSecret": "RdJKBDkJZslrgON3WgsIDzaKpBJvDRd37xwRAOd0",
    "bucket": "ruoyi-vue-pro",
    "endpoint": "10.165.8.176:8080",
    "domain": "http://10.165.8.176:8080",
    "region": ""
  }
}

### 请求 /infra/file-config/test 接口 => 成功
GET {{baseUrl}}/infra/file-config/test?id=2
Content-Type: application/json
tenant-id: {{adminTenentId}}
Authorization: Bearer {{token}}
